export const REMOTE_SERVER_URL = process.env.VUE_APP_REMOTE_SERVER_URL;
export const REMOTE_API_SERVER_URL = REMOTE_SERVER_URL;
export const REMOTE_THEME_SOURCE_URL = process.env.VUE_APP_REMOTE_THEME_SOURCE_URL;
export const STATIC_RESOURCE_URL = process.env.VUE_APP_STATIC_RESOURCE_URL;
export const BASE_URL = process.env.VUE_APP_BASE_URL;
